CREATE TABLE CREW_BOARD(
	ID INT PRIMARY KEY,
	WRITER VARCHAR(100),
	CONTENT VARCHAR(200),
	TITLE VARCHAR(50) NOT NULL
);
ALTER TABLE CREW_BOARD
ADD CONSTRAINT FK_CREW_BOARD_WRITER
FOREIGN KEY (WRITER)
REFERENCES MEMBER(ID)
ON DELETE CASCADE;

INSERT INTO CREW_BOARD(ID,WRITER,CONTENT,TITLE)
VALUES ((SELECT NVL(MAX(ID),0)+1 FROM CREW_BOARD),'샘플유저1','샘플내용1','샘플제목1');
INSERT INTO CREW_BOARD(ID,WRITER,CONTENT,TITLE)
VALUES ((SELECT NVL(MAX(ID),0)+1 FROM CREW_BOARD),'샘플유저2','샘플내용2','샘플제목2');
INSERT INTO CREW_BOARD(ID,WRITER,CONTENT,TITLE)
VALUES ((SELECT NVL(MAX(ID),0)+1 FROM CREW_BOARD),'샘플유저3','샘플내용3','샘플제목3');
INSERT INTO CREW_BOARD(ID,WRITER,CONTENT,TITLE)
VALUES ((SELECT NVL(MAX(ID),0)+1 FROM CREW_BOARD),'샘플유저4','샘플내용4','샘플제목4');
INSERT INTO CREW_BOARD(ID,WRITER,CONTENT,TITLE)
VALUES ((SELECT NVL(MAX(ID),0)+1 FROM CREW_BOARD),'샘플유저5','샘플내용5','샘플제목5');
INSERT INTO CREW_BOARD(ID,WRITER,CONTENT,TITLE)
VALUES ((SELECT NVL(MAX(ID),0)+1 FROM CREW_BOARD),'샘플유저6','샘플내용6','샘플제목6');

SELECT --전체글 출력
	C.ID,
	M.NAME,
	C.CONTENT,
	C.TITLE
FROM 
	CREW_BOARD C
JOIN 
    MEMBER M
ON 
    C.WRITER = M.ID

SELECT ID,NAME,CONTENT,TITLE --최신글5개만 출력
FROM (
    SELECT 
    	C.ID,
   		M.NAME,
   		C.CONTENT,
   		C.TITLE
    FROM 
    	CREW_BOARD C
    JOIN 
    	MEMBER M
    ON 
    	C.WRITER = M.ID
    ORDER BY C.ID DESC
) 
WHERE 
	ROWNUM <= 5;
	
SELECT --PK로 검색
	C.ID,
	M.NAME,
	C.CONTENT,
	C.TITLE
FROM 
	CREW_BOARD C
JOIN 
    MEMBER M
ON 
    C.WRITER = M.ID
WHERE
	C.ID=1;


SELECT * FROM CREW_BOARD;

DROP TABLE CREW_BOARD;