@남상도 CREATE TABLE BOARD (
    BOARD_NUM INT PRIMARY KEY,      -- 게시글의 고유 식별자 (기본키)
    BOARD_TITLE VARCHAR(100) NOT NULL,    -- 게시글 제목
    BOARD_CONTENT VARCHAR(1000),          -- 게시글 내용 (NULL 허용)
    BOARD_CNT INT DEFAULT 0,           -- 조회수 (기본값 0)
    BOARD_LOCATION VARCHAR(100) NOT NULL, -- 게시글 지역
    BOARD_WRITER_ID VARCHAR(100),   -- 글 작성자의 FK (외래키)
    -- 외래키 제약조건 설정
    CONSTRAINT FK_BOARD_MEMBER_ID 
    FOREIGN KEY (BOARD_MEMBER_ID)
    REFERENCES MEMBER(ID)           -- BOARD_MEMBER_ID가 MEMBER 테이블의 ID를 참조
    ON DELETE CASCADE               -- MEMBER가 삭제되면 BOARD도 삭제
);

-- 샘플 데이터 삽입
INSERT INTO BOARD (BOARD_NUM,BOARD_TITLE,BOARD_CONTENT,BOARD_LOCATION,BOARD_WRITER_ID)
VALUES ((SELECT NVL(MAX(BOARD_NUM),0)+1 FROM BOARD), 'board_title1', 'board_content1', 'board_location1', '샘플유저1');
INSERT INTO BOARD (BOARD_NUM,BOARD_TITLE,BOARD_CONTENT,BOARD_LOCATION,BOARD_WRITER_ID)
VALUES ((SELECT NVL(MAX(BOARD_NUM),0)+1 FROM BOARD), 'board_title2', 'board_content2', 'board_location2', '샘플유저2');
INSERT INTO BOARD (BOARD_NUM,BOARD_TITLE,BOARD_CONTENT,BOARD_LOCATION,BOARD_WRITER_ID)
VALUES ((SELECT NVL(MAX(BOARD_NUM),0)+1 FROM BOARD), 'board_title3', 'board_content3', 'board_location3', '샘플유저3');
INSERT INTO BOARD (BOARD_NUM,BOARD_TITLE,BOARD_CONTENT,BOARD_LOCATION,BOARD_WRITER_ID)
VALUES ((SELECT NVL(MAX(BOARD_NUM),0)+1 FROM BOARD), 'board_title4', 'board_content4', 'board_location4', '샘플유저4');
INSERT INTO BOARD (BOARD_NUM,BOARD_TITLE,BOARD_CONTENT,BOARD_LOCATION,BOARD_WRITER_ID)
VALUES ((SELECT NVL(MAX(BOARD_NUM),0)+1 FROM BOARD), 'board_title5', 'board_content5', 'board_location5', '샘플유저5');
INSERT INTO BOARD (BOARD_NUM,BOARD_TITLE,BOARD_CONTENT,BOARD_LOCATION,BOARD_WRITER_ID)
VALUES ((SELECT NVL(MAX(BOARD_NUM),0)+1 FROM BOARD), 'board_title6', 'board_content6', 'board_location6', '샘플유저6');




-- 최신글 5개 검색 SelectAll(ALLROWNUM)
SELECT 
    BOARD_NUM,
    BOARD_TITLE,
    BOARD_CONTENT,
    BOARD_CNT,
    BOARD_LOCATION,
    BOARD_WRITER_ID
FROM (
    SELECT 
        B.BOARD_NUM, 
        B.BOARD_TITLE, 
        B.BOARD_CONTENT, 
        B.BOARD_CNT, 
        B.BOARD_LOCATION, 
        B.BOARD_WRITER_ID
    FROM 
        BOARD B
    JOIN 
        MEMBER M
    ON 
        B.BOARD_WRITER_ID = M.MEMBER_ID
    ORDER BY 
        B.BOARD_NUM DESC
)
WHERE ROWNUM <= 5;  
    
-- 전체글 출력 SelectAll (ALL)
SELECT BOARD_NUM,BOARD_TITLE,BOARD_CONTENT,BOARD_CNT,BOARD_LOCATION,BOARD_WRITER_ID FROM BOARD;

-- 특정 게시글 상세조회 SelectONE(__)
SELECT BOARD_NUM,BOARD_TITLE,BOARD_CONTENT,BOARD_CNT,BOARD_LOCATION,BOARD_WRITER_ID FROM BOARD WHERE BOARD_NUM = 1; 

--목록 출력검색 SelectAll(SERCH_ID)
SELECT 
    B.BOARD_NUM,
    B.BOARD_TITLE,
    B.BOARD_CONTENT,
    B.BOARD_CNT,
    B.BOARD_LOCATION,
    B.BOARD_WRITER_ID
FROM 
    BOARD B
JOIN
   MEMBER M
ON
   M.MEMBER_ID = B.BOARD_WRITER_ID
WHERE 
    B.BOARD_WRITER_ID = '샘플유저1';
   
-- 게시글 삭제 Delete
DELETE FROM BOARD WHERE BOARD_NUM = 1;

-- 전체 글의 개수 조회 SelectOne(ALLCOUNT)
SELECT COUNT(*) FROM BOARD;

-- BOARD 테이블 삭제
DROP TABLE BOARD;