CREATE TABLE MEMBER(
	ID VARCHAR(100) PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	PHONENUMBER VARCHAR(50) NOT NULL,
	MDATE DATE DEFAULT SYSDATE,
	PROFILE VARCHAR(2048) DEFAULT NULL,
	CURRENT_POINT INT DEFAULT 0,
	TOTAL_POINT INT DEFAULT 0,
	CREW_ID INT DEFAULT NULL,
	CDATE DATE DEFAULT NULL,
	LOCATION VARCHAR(100) NOT NULL
);
ALTER TABLE MEMBER
ADD CONSTRAINT FK_CREW_ID
FOREIGN KEY (CREW_ID)
REFERENCES CREW(ID)
ON DELETE SET NULL;

INSERT INTO MEMBER(ID,NAME,PASSWORD,PHONENUMBER,LOCATION) 
VALUES('샘플유저1','샘플이름1','샘플비밀번호1','샘플번호1','샘플지역1');
INSERT INTO MEMBER(ID,NAME,PASSWORD,PHONENUMBER,LOCATION) 
VALUES('샘플유저2','샘플이름2','샘플비밀번호2','샘플번호2','샘플지역2');
INSERT INTO MEMBER(ID,NAME,PASSWORD,PHONENUMBER,LOCATION) 
VALUES('샘플유저3','샘플이름3','샘플비밀번호3','샘플번호3','샘플지역3');

SELECT ID,NAME,PHONENUMBER,PROFILE,MDATE,CURRENT_POINT,TOTAL_POINT,CREW_ID,CDATE,LOCATION
FROM MEMBER
WHERE ID = '샘플유저1';

SELECT ID,NAME,PHONENUMBER,PROFILE,MDATE,CURRENT_POINT,TOTAL_POINT,CREW_ID,CDATE,LOCATION
FROM MEMBER
WHERE ID = '샘플유저1' AND PASSWORD='샘플비밀번호1';

SELECT ID,NAME,PHONENUMBER,PROFILE,MDATE,CURRENT_POINT,TOTAL_POINT,CREW_ID,CDATE,LOCATION,MDATE
FROM MEMBER
WHERE CREW_ID = NULL;

SELECT ID, NAME, PASSWORD, PHONENUMBER, MDATE, PROFILE, CURRENT_POINT, TOTAL_POINT, CREW_ID, CDATE, LOCATION
FROM MEMBER
ORDER BY TOTAL_POINT DESC;

DELETE FROM MEMBER WHERE ID = '샘플유저1';

UPDATE MEMBER
SET
	NAME = '샘플이름1',
	PROFILE = NULL,
	PHONENUMBER = '샘플번호11',
	LOCATION = '샘플지역11',
	--CREW_ID = 1
	CDATE = SYSDATE
WHERE ID = '샘플유저2'

UPDATE MEMBER
SET
	CREW_ID = ?,
	CDATE = SYSDATE
WHERE ID = ?

SELECT * FROM MEMBER;

DROP TABLE MEMBER;